### PR TITLE
Grid layout

### PR DESCRIPTION
**Pull request by JLSJamesShi**
Changed the layout algorithm to work specifically for Grid layout.
Column and row span support has been implemented as specified in @sunjay's comment in 
https://github.com/ProtoArt/spritec/issues/153#issuecomment-592956258.

### CODE REVIEW

**Review by sunjay — APPROVED** [review]
Great work @JLSJamesShi! Your code has gotten really impressive! The only changes we made during review were very minor. Keep up the great work! :tada:

**Comment by sunjay** [comment]
@daose Can you approve this PR? I made some changes in spritec_binding and I want to make sure they're correct. See: https://github.com/ProtoArt/spritec/pull/213/commits/bedb83e12485aa54604252de6d780dd26141b485

**Comment by sunjay** [comment]
This PR is good to merge as soon as the build passes and @daose gives us the OK.

**Review by daose — APPROVED** [review]
thanks @sunjay , made a fix on top, LGTM

**Comment by sunjay** [comment]
Congrats @JLSJamesShi!! 🎉🎉🎉

**Pull request merged**
