### PR TITLE
add spritec_binding as a member of spritec workspace

### PR DESCRIPTION
**Pull request by daose**
This way they can share the same versions of dependency if I end up needing to use `gltf` crate in spritec_binding as well.

But also prevents a lonely `spritec_binding/native/Cargo.lock` file from being outdated when spritec updates.

### CODE REVIEW

**Review by sunjay — APPROVED** [review]
Nice! I was under the impression that cdylib crates can't be part of workspaces. I can't seem to find where I saw that though, so I guess as long as the build passes this is good to go.

Thanks for making this change @daose! :tada:

**Comment by sunjay** [comment]
@daose `--release` can increase build times significantly. What do you think about trying the workaround here: https://github.com/neon-bindings/neon/issues/463#issuecomment-552232421?

**Comment by daose** [comment]
Currently window builds will fail if not built with `--release` due to a `compile_error!` macro getting triggered. I'm not sure how enabling debug assertions on release builds can help it pass.

I've lessened the impact by making it only affect windows platform but not sure what else I can do.

**Comment by sunjay** [comment]
> Currently window builds will fail if not built with `--release` due to a `compile_error!` macro getting triggered. I'm not sure how enabling debug assertions on release builds can help it pass.
> 
> I've lessened the impact by making it only affect windows platform but not sure what else I can do.

Okay no problem. The workaround was listed in the same issue you linked to, so I thought it might be worth a shot to see if it fixes the problem without requiring a release build.

**Pull request merged**
