### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by sunjay**
Am I a microsoft shill now? I guess we'll find out. ;)

I am using Azure Pipelines for other projects and I think it might be good to see if we can use it to do cross platform builds on Windows, Mac, and Linux. Our current Travis CI setup only runs Linux builds.

This PR is for me to experiment with it and see what happens.

### CODE REVIEW

**Comment by sunjay** [comment]
The build looks great! With this we can even detect regressions on nightly and fix them before they hit stable. I'm very happy with this and will probably merge it tomorrow.

cc @ProtoArt/core-team

**Comment by daose** [comment]
nightly builds seem to be failing on clippy

**Comment by sunjay** [comment]
Yup. That's fine. It's pretty common to make the stable and beta builds mandatory and the nightly build optional (since nightly is where breakages are expected). The nightly is broken because the currently released nightly doesn't actually have clippy. Future nightlies will fix that, and the nightly build will pass for those.

**Comment by sunjay** [comment]
@daose Just a follow-up about this. I re-ran the failed nightly builds today and they passed: https://dev.azure.com/ProtoArt/spritec/_build/results?buildId=18&view=results

**Pull request merged**
